package cc.co.llabor.cache;

public class Config {

	public static String CALC_DEFAULT_WORKDIR() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:00:20 PM ;)!");
			else
				/*return*/ return null; 
	}

 
}
