package eu.blky.net.http;

import net.sf.jsr107cache.Cache;

public class Manager {

	public static Cache getCache(String cacheName) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018 ;)!");
			else
				return null;
	}

 

}
