package eu.blky.net.http;

import java.io.InputStream;

public class MemoryFileItem {

	public String getName() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018 ;)!");
			else
				return null;
	}

	public InputStream getInputStream() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018 ;)!");
			else
				return null;
	}

	public String getFieldName() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018 ;)!");
			else
				return null;
	}

	public String getContentType() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 9:12:43 AM ;)!");
			else
				return null;
	}
 

 

}
