package org.vietspider.html.util;

public interface JSStore {

	static JSStore getInstanse() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 10:55:52 AM ;)!");
			else
				return null;
	}

	Item putOrCreate(String cacheKey, String scriptValue, String xRef);

}
