package eu.blky.net.http;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Locale;
import java.util.Properties;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletResponse;

public class FakeHttpServletResponse implements HttpServletResponse {

	private OutputStream oaosPar;
	private Properties headers= new Properties();
	private String contenttype;
	private String charenc;

	public FakeHttpServletResponse(ByteArrayOutputStream oaosPar) {
		this.oaosPar = oaosPar;
	}

	@Override
	public void flushBuffer() throws IOException {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public int getBufferSize() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return 0; 
	}

	@Override
	public String getCharacterEncoding() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public Locale getLocale() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public ServletOutputStream getOutputStream() throws IOException {
		 return new MyServletOutputStream( oaosPar ); 
	}

	@Override
	public PrintWriter getWriter() throws IOException {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public boolean isCommitted() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return false; 
	}

	@Override
	public void reset() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void resetBuffer() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void setBufferSize(int arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void setContentLength(int arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
  
	}

	@Override
	public void setContentType(String arg0) {
		this.contenttype = arg0 ;
	 
	}

	@Override
	public void setLocale(Locale arg0) {
		// TODO Auto-generated method stub
		if (1 == 1) 
			throw new RuntimeException(
						"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void addCookie(Cookie arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
	  
	}

	@Override
	public void addDateHeader(String arg0, long arg1) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
		  
	}

	@Override
	public void addHeader(String arg0, String arg1) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
	 
	}

	@Override
	public void addIntHeader(String arg0, int arg1) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public boolean containsHeader(String arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return false; 
	}

	@Override
	public String encodeRedirectURL(String arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public String encodeRedirectUrl(String arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public String encodeURL(String arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public String encodeUrl(String arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public void sendError(int arg0) throws IOException {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void sendError(int arg0, String arg1) throws IOException {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
   
	}

	@Override
	public void sendRedirect(String arg0) throws IOException {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void setDateHeader(String arg0, long arg1) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
  
	}

	@Override
	public void setHeader(String key, String value) {
		this.headers.put(key, value);
 
	}

	@Override
	public void setIntHeader(String arg0, int arg1) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void setStatus(int arg0) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public void setStatus(int arg0, String arg1) {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 2:36:00 PM ;)!");
 
	}

	@Override
	public String getContentType() {
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 21, 2018, 3:55:51 PM ;)!");
			else
				/*return*/ return null; 
	}

	@Override
	public void setCharacterEncoding(String arg0) {
		this.charenc = arg0;
		  
	}

}
