package eu.blky.net.http;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.io.Serializable;
import java.util.Collection;
import java.util.Locale;
import java.util.Properties;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletResponse;

public class FetchObj implements Serializable , HttpServletResponse{
	private ByteArrayOutputStream oaosPar;
	private Properties headers= new Properties();
	private String contenttype;
	private String charenc;
	
	 
	public byte[] getBytes() {
		return this.oaosPar.toByteArray();
	}
	public String getContenttype() {
		return contenttype;
	}

	public void setContenttype(String contenttype) {
		this.contenttype = contenttype;
	}

	public String getCharenc() {
		return charenc;
	}

	public void setCharenc(String charenc) {
		this.charenc = charenc;
	}
	
	public FetchObj(ByteArrayOutputStream myBAOS) {
		this.oaosPar = myBAOS;
		 
	}

	public byte[] getData() {
		return getBytes(); 
	}
	@Override
	public void setContentType(String arg0) {
		this.setContenttype(arg0) ;
	 
	}
	
	@Override
	public void setCharacterEncoding(String arg0) {
		this.setCharenc(arg0);
		  
	}	
	@Override
	public ServletOutputStream getOutputStream() throws IOException {
		 return new MyServletOutputStream( oaosPar ); 
	}
 
	@Override
	public void setHeader(String key, String value) {
		this.headers.put(key, value);
 
	}
	 

	@Override
	public String getContentType() {
		return this.contenttype; 
	}

	 
	private  static void callDebugger(){
		System.out.println("set debug breakpoint here for activate DEBUG");
		
	}
	@Override
	public void flushBuffer() throws IOException {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public int getBufferSize() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return 0; 
	}
	@Override
	public String getCharacterEncoding() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Locale getLocale() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public PrintWriter getWriter() throws IOException {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public boolean isCommitted() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return false; 
	}
	@Override
	public void reset() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void resetBuffer() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setBufferSize(int arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setContentLength(int arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setContentLengthLong(long arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setLocale(Locale arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void addCookie(Cookie arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void addDateHeader(String arg0, long arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void addHeader(String arg0, String arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void addIntHeader(String arg0, int arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public boolean containsHeader(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return false; 
	}
	@Override
	public String encodeRedirectURL(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public String encodeRedirectUrl(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public String encodeURL(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public String encodeUrl(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public String getHeader(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Collection<String> getHeaderNames() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Collection<String> getHeaders(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public int getStatus() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/ return 0; 
	}
	@Override
	public void sendError(int arg0) throws IOException {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void sendError(int arg0, String arg1) throws IOException {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void sendRedirect(String arg0) throws IOException {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setDateHeader(String arg0, long arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setIntHeader(String arg0, int arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setStatus(int arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}
	@Override
	public void setStatus(int arg0, String arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Nov 25, 2018, 6:07:56 PM ;)!");
			 
			/*return*/  
	}



}
